port: /dev/ttyUSB0

joint_order: [waist]
sleep_positions: [0]

joint_state_publisher:
  update_rate: 30
  publish_states: true
  topic_name: joint_states

groups:
  arm: [waist]

grippers:

shadows:

sisters:

motors:
  waist:
    ID: 1
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255
