port: /dev/ttyUSB0

joint_order: [Joint1, Joint2, Joint3, Joint4, Joint5, Joint6, gripper]
sleep_positions: [0, 0.785398, 0.785398, 0, 1.5708, 0, 0]

joint_state_publisher:
  update_rate: 30
  publish_states: true
  topic_name: joint_states

groups:
  arm: [Joint1, Joint2, Joint3, Joint4, Joint5, Joint6]

grippers:
  gripper:
    horn_radius: 0.022
    arm_length: 0.036
    left_finger: GL
    right_finger: GR

shadows:
  Joint2:
    shadow_list: [Joint2_shadow]
    calibrate: true

sisters:

motors:
  Joint1:
    ID: 1
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 1024
    Max_Position_Limit: 3072
    Secondary_ID: 255
    
  Joint2:
    ID: 2
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 1024
    Max_Position_Limit: 2818
    Secondary_ID: 255

  Joint2_shadow:
    ID: 3
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 1024
    Max_Position_Limit: 2818
    Secondary_ID: 2

  Joint3:
    ID: 4
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 2105
    Max_Position_Limit: 4038
    Secondary_ID: 255

  Joint4:
    ID: 5
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  Joint5:
    ID: 6
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 2048
    Max_Position_Limit: 4095
    Secondary_ID: 255
    
  Joint6:
    ID: 7
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  gripper:
    ID: 8
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 4 
    Velocity_Limit: 131
    Min_Position_Limit: 558
    Max_Position_Limit: 4095
    Secondary_ID: 255
