groups:
  arm:
    operating_mode: position
    profile_type: time
    profile_velocity: 33
    profile_acceleration: 10
    torque_enable: true

singles:
  gripper:
    operating_mode: pwm
    torque_enable: true
