port: /dev/tty_STUDENT_ARM_LEFT

groups:
  arm:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 50
    profile_acceleration: 10
    torque_enable: true
    
singles:
  gripper:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 0
    profile_acceleration: 0
    torque_enable: true
